# Generated by Django 4.2.7 on 2023-12-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
