# Generated by Django 4.2.7 on 2024-07-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usermodel_phone_number_usermodel_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='retries',
            field=models.IntegerField(default=0),
        ),
    ]
