name: django-auth
on: push

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: test the application
  #       run: |
  #         docker build -t django-auth-test -f Dockerfile.test .
  #         docker run django-auth-test
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_required_version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: get required version
        id: get_required_version
        run: |
          version=$(bash djangoAuthApp/scripts/get-version.sh "${{ github.event.head_commit.message }}")
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "version=$version" >> "$GITHUB_ENV"
      - name: update git repo
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "thehunter597777@gmail.com"
          git config --global user.name "TheHunter597"
          echo $GITHUB_TOKEN | gh auth login --with-token
          git add .
          git commit -m "Bump version to ${{ steps.get_required_version.outputs.version }} [skip ci] "
          git push
      # - name: build docker image
      #   run: |
      #     docker build -t ecommercemainreg.azurecr.io/auth:${{ env.version }} -f Dockerfile .
      # - uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - name: adding containers registry
      #   run: |
      #     az acr login --name ecommercemainreg
      #     docker push ecommercemainreg.azurecr.io/auth:${{ env.version }}
