name: django-auth
on: push

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: test the application
  #       run: |
  #         docker build -t django-auth-test -f Dockerfile.test .
  #         docker run django-auth-test
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      version: ${{ steps.get_required_version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: get required version
        id: get_required_version
        run: |
          version=$(bash djangoAuthApp/scripts/get-version.sh "${{ github.event.head_commit.message }}")
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "version=$version" >> "$GITHUB_ENV"

      - uses: qoomon/actions--setup-git@v1
        with:
          user: actor
      - name: update git
        run: |
          git add .
          git commit -m "version ${{ steps.get_required_version.outputs.version }}"
          git push
      # - name: build docker image
      #   run: |
      #     docker build -t ecommercemainreg.azurecr.io/auth:${{ env.version }} -f Dockerfile .
      # - uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - name: adding containers registry
      #   run: |
      #     az acr login --name ecommercemainreg
      #     docker push ecommercemainreg.azurecr.io/auth:${{ env.version }}
